# Generated by Django 4.2 on 2023-05-01 08:51

import baham.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, unique=True)),
                ('password_hash', models.CharField(max_length=512, unique=True)),
                ('first_name', models.CharField(max_length=50, unique=True)),
                ('last_name', models.CharField(max_length=50, unique=True)),
                ('birthdate', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('email', models.EmailField(max_length=254)),
                ('primary_contact', models.CharField(max_length=20, unique=True)),
                ('alternate_contact', models.CharField(max_length=20, null=True, unique=True)),
                ('address', models.CharField(max_length=255)),
                ('address_latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('address_longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('landmark', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=True)),
                ('date_deactivated', models.TextField()),
                ('bio', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='VehicleModel',
            fields=[
                ('Model_id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('vendor', models.CharField(max_length=20)),
                ('model', models.CharField(max_length=20)),
                ('type', models.CharField(choices=[('AUTO_RICKSHAW', 'Auto Rickshaw'), ('SEDAN', 'Sedan'), ('HATCHBACK', 'Hatch Back'), ('SUV', 'Sub_Urban Vehicle'), ('VAN', 'Van'), ('HIGH_ROOF', 'High Roof'), ('MOTORCYCLE', 'Motor cycle/Scooter')], help_text='Select the vehicle chasis type', max_length=50)),
                ('capacity', models.PositiveSmallIntegerField(default=2)),
            ],
            options={
                'db_table': 'baham_vehicle_model',
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('vehicle_id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('registration_number', models.CharField(help_text='Unique registration/license plate no. of the vehicle.', max_length=10, unique=True)),
                ('Colour', models.CharField(default='white', max_length=50, validators=[baham.models.validate_colour])),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('FULL', 'Full'), ('INACTIVE', 'Inactive'), ('REMOVED', 'Removed')], max_length=50)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baham.vehiclemodel')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baham.user')),
            ],
        ),
    ]
